version: 2.0

# Default actions to perform on each Emacs version
default: &default-steps
  steps:
    - checkout
    - run: apt-get update && apt-get install make
    - run: make version
    - run: make lint

# Enumerated list of Emacs versions
jobs:
  test-emacs-25:
    docker:
      - image: silex/emacs:25.3
        entrypoint: bash
    <<: *default-steps

  test-emacs-26:
    docker:
      - image: silex/emacs:26.2
        entrypoint: bash
    <<: *default-steps

  test-emacs-master:
    docker:
      - image: silex/emacs:master
        entrypoint: bash
    <<: *default-steps

# Executing in parallel
workflows:
  version: 2
  ci-test-matrix:
    jobs:
      - test-emacs-25
      - test-emacs-26
      - test-emacs-master
